# Generated by Django 4.0.4 on 2022-05-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='imię')),
                ('last_name', models.CharField(max_length=100, verbose_name='nazwisko')),
                ('about', models.TextField(blank=True, verbose_name='o reżyserze')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='zdjęcie')),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='published_at',
            field=models.DateField(verbose_name='data premiery'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='short_description',
            field=models.TextField(verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100, verbose_name='tytuł'),
        ),
    ]
